/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

package main

import "fmt"

func triangle(n int) int {
	return ((n * (n + 1)) / 2)
}

func pentagonal(n int) int {
	return ((n * (3*n - 1)) / 2)
}

func triPenHex(t, p, h int) (int, int, int) {
	h++
	hexa := n * (2*n - 1)
	for pentagonal(p) < hexa {
		p++
	}
	for triangle(t) < hexa {
		t++
	}
	if hexa == pentagonal(p) && hexa == triangle(t) {
		return t, p, h
	} else {
		return triPenHex(t, p, h)
	}
}

func main() {
	t, _, _ := triPenHex(285, 165, 143)
	fmt.Println(triangle(t))
}
