/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

package algo

import (
	"fmt"
)

func E44() {
	found := false
	i := 3
	for !found {
		for j := 2; j < i; j++ {
			if isPentagonal(Pentagonal(i)+Pentagonal(j)) && isPentagonal(Pentagonal(i)-Pentagonal(j)) {
				fmt.Printf("P%d + and - P%d is pentagonal, D = %d\n", i, j, Pentagonal(i)-Pentagonal(j))
				found = true
			}
		}
		i++
	}
}

func isPentagonal(number int) bool {
	pentagonalNumber := 1
	for i := 1; pentagonalNumber < number; i++ {
		pentagonalNumber = i * (3*i - 1) / 2
	}
	if number == pentagonalNumber {
		return true
	} else {
		return false
	}
}
