/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

package algo

import "fmt"

func E45() {
	t, _, _ := triPenHex(285, 165, 143)
	fmt.Println(Triangle(t))
}

func triPenHex(t, p, h int) (int, int, int) {
	h++
	hexa := h * (2*h - 1)
	for Pentagonal(p) < hexa {
		p++
	}
	for Triangle(t) < hexa {
		t++
	}
	if hexa == Pentagonal(p) && hexa == Triangle(t) {
		return t, p, h
	} else {
		return triPenHex(t, p, h)
	}
}
